### ISSUE TITLE
"Exceeded maxRedirects" after some EventEmitter warning

### ISSUE THREAD

**Issue by remagio** [edsu/earls#12]
Looks like when growing listeners it starts soon getting exceeded max redirects. Checking around looks like maxRedirects value is related to cumulative requests.

```
==> /var/log/supervisor/botlersec_err.log <==
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:160:15)
    at Request.init (/pub/botlersec/earls/node_modules/request/request.js:618:8)
    at Request.onRequestResponse (/pub/botlersec/earls/node_modules/request/request.js:1127:10)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
    at CleartextStream.read [as _read] (tls.js:511:12)
    at CleartextStream.Readable.read (_stream_readable.js:323:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:160:15)
    at Request.start (/pub/botlersec/earls/node_modules/request/request.js:937:8)
    at Request.end (/pub/botlersec/earls/node_modules/request/request.js:1635:10)
    at end (/pub/botlersec/earls/node_modules/request/request.js:676:14)
    at Object._onImmediate (/pub/botlersec/earls/node_modules/request/request.js:690:7)
    at processImmediate [as _immediateCallback] (timers.js:336:15)

==> /var/log/supervisor/botlersec.log <==
error while processing url: Error: Exceeded maxRedirects. Probably stuck in a redirect loop https://careers.hawaiipacifichealth.org:443/sso/SSOServlet?_action=LOGINASSERT&_ssoOrigUrl=https%3A%2F%2Fcareers.hawaiipacifichealth.org%3A443%2Fltmprod%2FCandidateSelfService%2Fcontroller.servlet%3Fcontext.dataarea%3Dltmprod%26webappname%3DCandidateSelfService%26context.session.key.HROrganization%3D10%26context.session.key.JobBoard%3DEXTERNAL%26_saveKeys%3Dtrue%26JobPost%3D1%26JobReq%3D2836%26context.session.key.noheader%3Dtrue&_TKM=TODO-UI&_serviceName=LTMPROD.HCMAPP.CANDIDATESELFSERVICE&_ssoTenant=DEFAULT&_ssovaltoken=oJXE4AkEm0%2FkR1Pm%2F826LV%2FKZ4g%3D
processing tweet: 574722943038586880
```

**Comment by edsu** [comment]
This must've been an intermittent problem on the washingtontimes website. I was able to process this tweet just fine now:

```
processing tweet: 574722943038586880
queueing lookup for http://www.washingtontimes.com/news/2015/mar/8/released-guantanamo-bay-prisoners-likely-resume-fi/
looking up url: http://www.washingtontimes.com/news/2015/mar/8/released-guantanamo-bay-prisoners-likely-resume-fi/
tallying:  http://www.washingtontimes.com/news/2015/mar/8/released-guantanamo-bay-prisoners-likely-resume-fi/ Released Guantanamo Bay prisoners likely resume fighting U.S. - Washington Times MichaelEClark_ https://twitter.com/MichaelEClark_/statuses/574722943038586880
finished processing url: http://www.washingtontimes.com/news/2015/mar/8/released-guantanamo-bay-prisoners-likely-resume-fi/
```
